version: '3'
services:
  jenkins:
    container_name: Jenkins_managed_by_compose
    image: jenkins/jenkins:alpine
    ports:
      - "8001:8080"
      - "5001:50000"
    volumes:
      - jenkins_home:/var/Jenkins_home
    restart: always
    networks:
      - net_jenkins
volumes:
  jenkins_home:
networks:
  net_jenkins:
